---
name: Codestyle
on:
  - push
  - pull_request

jobs:
  cabal-fmt:
    name: Lint Cabal project description using cabal-fmt
    runs-on: ubuntu-20.04
    steps:
      - name: Cache Cabal files
        uses: actions/cache@v3.2.4
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-cabal

      - name: Install cabal-fmt
        run: |
          cabal update
          cabal install "cabal-fmt-0.1.6"
          echo "$HOME/.cabal/bin" >> $GITHUB_PATH

      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: Check formatting of Cabal project descriptions
        run: |
          for project in lawful-classes-types lawful-classes-hedgehog lawful-classes-quickcheck lawful-classes-demo; do
            cabal-fmt --Werror --check $project/$project.cabal
          done
